---
version: 2

# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
# check-jsonschema --schemafile https://json.schemastore.org/dependabot-2.0.json .github/dependabot.yml

# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
# https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configuring-multi-ecosystem-updates
#
multi-ecosystem-groups:
  infrastructure:
    schedule:
      # interval: "weekly"
      interval: "daily"
    labels: ["infrastructure", "dependencies"]
    open-pull-requests-limit: 3
    target-branch: "main"
    commit-message:
      prefix: "dbot/fix"
      prefix-development: "dbot/chore"
      include: "scope" # Append (deps) or (deps-dev) to prefix



updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
    # commit-message:
    #   prefix: "dbot/fix"
    #   prefix-development: "dbot/chore"
    #   include: "scope" # Append (deps) or (deps-dev) to prefix
    # open-pull-requests-limit: 3
    # target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    multi-ecosystem-group: "infrastructure"
    patterns:
      - "*"
    # groups:
    #   pypkg:
    #     patterns:
    #       - "*"
    #   minor-and-patch:
    #     applies-to: version-updates
    #     patterns:
    #       - "*"
    #     update-types:
    #       # - "major"
    #       - "minor"
    #       - "patch"
    # ignore:
    #     - dependency-name: "*"
    #       update-types:
    #         - "version-update:semver-major"
          # grouped: false


  - package-ecosystem: "terraform"
    directories:
      - "/terraform"
    schedule:
      interval: "daily"
    # commit-message:
    #   prefix: "dbot/fix"
    #   prefix-development: "dbot/chore"
    #   include: "scope" # Append (deps) or (deps-dev) to prefix
    labels:
      - "dependencies"
      - "terraform"
    multi-ecosystem-group: "infrastructure"
    patterns:
      - "*"
    # groups:
    #   tf-version:
    #     applies-to: version-updates
    #     patterns:
    #       - "*"
    #     update-types:
    #       - "minor"
    #       - "patch"
    #   tf-security:
    #     applies-to: security-updates
    #     patterns:
    #       - "*"
    #       # - "aws"
    #       # - "terraform-*"
    #     update-types:
    #       - "minor"
    #       - "patch"

  - package-ecosystem: npm
    directories:
      - "/devplatform/devplatform"
      - "/devplatform/sam-pipeline"
    schedule:
      interval: "daily"
    # commit-message:
    #   prefix: "dbot/fix"
    #   prefix-development: "dbot/chore"
    #   include: "scope" # Append (deps) or (deps-dev) to prefix
    labels:
      - "dependencies"
      - "npm"
    # multi-ecosystem-group: "infrastructure"
    # patterns:
    #   - "*"
    groups:
      npm:
        patterns:
          - '*'

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    multi-ecosystem-group: "infrastructure"
    patterns:
      - "*"
    # groups:
    #   gha-version:
    #     applies-to: version-updates
    #     patterns:
    #       - "*"
    #     update-types:
    #       - "minor"
    #       - "patch"
    #   gha-security:
    #     applies-to: security-updates
    #     patterns:
    #       - "*"
    #     update-types:
    #       - "minor"
    #       - "patch"
